apiVersion: apps/v1
kind: Deployment
metadata:
  name: faveo-cron
  namespace: faveo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faveo-cron
  template:
    metadata:
      labels:
        app: faveo-cron
    spec:
      containers:
        - name: faveo-cron
          image: harbor.faveotools.com/new_k8s/cron:1
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: volume-data
              mountPath: /var/www/html
            - name: cm
              mountPath: /var/www/html/.env
              subPath: .env
      initContainers:
        - name: fetch
          image: harbor.faveotools.com/new_k8s/fetcher:1
          securityContext:
            runAsUser: 0
          command: ['sh', '-c', 'apt update && apt install git unzip curl -y && curl "https://billing.faveohelpdesk.com/download/faveo?order_number=33659383&serial_key=WZX5C1N4DABE0000" --output faveo.zip && unzip faveo.zip -d /var/www/html && chown -R www-data:www-data /var/www/html']
          volumeMounts:
            - name: volume-data
              mountPath: /var/www/html
      volumes:
        - name: volume-data
          emptyDir: {}
        - name: cm
          configMap:
            name: faveo-env